name: ci-test

#Main job is to test code

on: # Event that triggers the workflow
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest #runner

    services:
      # External services we want with job
      postgres:
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: root
          POSTGRES_DB: simple_bank
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.4" # Go version

      #- name: Build
      #  run: go build -v ./...

      - name: Run migation
        run: make migrateup

      - name: Test
        run: make test
#will fail at first since port 5433 not setup in test
# also perform migrations
