name: ci-test

on: # Event that triggers the workflow
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest #runner
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.4" # Go version

      #- name: Build
      #  run: go build -v ./...

      - name: Testxs
        run: make test
